[general]
live_config_reload = true

[env]
TERM = "xterm-256color"
# install terminfo to use
# TERM = "alactritty"

[window]
title = "Terminal"
decorations = "full"
dynamic_title = false
opacity = 0.90
blur = true

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 120
lines = 30

[font]
normal.family = "Iosevka"
bold.family = "Iosevka"
italic.family = "Iosevka"
bold_italic.family = "Iosevka"
size = 18.0

[cursor]
style = {  blinking = "Always" }

[scrolling]
history = 100000

[keyboard]
bindings = [
  { key = "Right", mods = "Alt",      chars = "\u001BF" },
  { key = "Left",  mods = "Alt",      chars = "\u001BB" },
]
